- hosts: frontends
  gather_facts: false
  tasks:
  - name: Use Uri module for wrting smoke test.
    uri:
      url: "http://{{ item }}"
    register: webpage
    with_items:
      - "{{ inventory_hostname }}"
  - debug: var=webpage.stdout
  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.content"
  - name: Success
    debug: msg="Congrats Yours HW Assignment is completed"
    
